export const ADD_ITEM = 'ADD_ITEM';
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS';
export const ADD_ITEM_ERROR = 'ADD_ITEM_ERROR';

export const START_DOWNLOAD_ITEMS = 'START_DOWNLOAD_ITEMS';
export const DOWNLOAD_ITEMS_SUCCESS = 'DOWNLOAD_ITEMS_SUCCESS';
export const DOWNLOAD_ITEMS_ERROR = 'DOWNLOAD_ITEMS_ERROR';

export const GET_ITEM_DELETE = 'GET_ITEM_DELETE';
export const ITEM_DELETE_SUCCESS = 'ITEM_DELETE_SUCCESS';
export const ITEM_DELETE_ERROR = 'ITEM_DELETE_ERROR';

export const GET_ITEM_EDIT = 'GET_ITEM_EDIT';
export const START_EDICION_ITEM = 'START_EDICION_ITEM';
export const ITEM_EDITED_SUCCESS = 'ITEM_EDITED_SUCCESS';
export const ITEM_EDITED_ERROR = 'ITEM_EDITED_ERROR';

export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'OCULTAR_ALERT';